### ISSUE TITLE
Does this support C++14?

### ISSUE THREAD

**Issue by SteveBronder** [r-lib/cpp11#100]
Sorry if this is a dumb question but is cpp11 safe to use when working with C++14/17 features?

**Comment by jimhester** [comment]
Yes, you just need to then set `C++14` in your `SystemRequirements` field in the `DESCRIPTION` file.

**Comment by SteveBronder** [comment]
Cool beans!

**Comment by jimhester** [comment]
No, it is not possible to do this currently.

Really for any non-trivial usage it is expected that you are writing an R package and I would really encourage you to do so if you are not.

**Comment by bgoodri** [comment]
Thanks. We have a package that uses Rcpp at runtime, but I was hoping I could use cpp11 with the C++14 standard to reduce the peak memory consumption.

Do you mean specifically that it would not be easy to get the `auto` return type to work for exported functions or that it would not be easy to get C++14 to work at all with `cpp_function`?

**Comment by jimhester** [comment]
Ah I see. I added a `cxx_std` argument that will allow you to control this.

Note however that you still can't use `auto` return types for functions registered by `[[cpp11::register]]`, however they can be used for all other functions without an issue.

**Comment by bgoodri** [comment]
Great! To make it feasible with `cpp11` chunks in vignettes, could the `cxx_std` argument instead default to `Sys.getenv("CXX_STD")` and then have `cxx_source` internally map to `"CXX11"` if `CXX_STD` was unset?

**Comment by jimhester** [comment]
Sure
