### ISSUE TITLE
license

### ISSUE THREAD

**Issue by jwijffels** [r-lib/cpp11#101]
Thanks for the package. 
I'm a happy Rcpp user and I wonder specifically about the license of the package 
- Rcpp has as license GPL-2 / GPL-3
- cpp11 is MIT licensed

What does this have as implication on R packages that link to cpp11. 
The Rcpp package has in it's documentation (copy pasted from https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf).

> 1.5. What licenses can I choose for my code. The Rcpp package is licensed under the terms of the GNU GPL 2 or later, just like R itself. A key goal of the Rcpp package is to make extending R more seamless. But by linking your code against R (as well as Rcpp), the combination is bound by the GPL as well. This is very clearly stated at the FSF website:
> Linking a GPL covered work statically or dynamically with other modules is making a combined work based on the GPL covered work. Thus, the terms and conditions of the GNU General Public License cover the whole combination.
> So you are free to license your work under whichever terms you find suitable (provided they are GPL-compatible, see the FSF site for details). However, the combined work will remain under the terms and conditions of the GNU General Public License. This restriction comes from both R which is GPL-licensed as well as from Rcpp and whichever other GPL-licensed components you may be linking against

Questions that pop up in my mind are:

1. Can you also state similar implications for cpp11
2. Are you planning to build an MIT version of R along with MIT version of packages base / stats and the like?

**Comment by jimhester** [comment]
The MIT license is not 'viral' like GPL, so there are no additional restrictions on what you link to cpp11. 

R itself is still GPL licensed of course, so your code would still would ultimately need to be GPL compatible, as it links to the R executable.

**Comment by jwijffels** [comment]
Ok clear. What about question 2.?

**Comment by jimhester** [comment]
No?

**Comment by jwijffels** [comment]
Ok. Thanks for the information!
