### ISSUE TITLE
Issues constructing a length 1 logical after r_bool introduction

### ISSUE THREAD

**Issue by jimhester** [r-lib/cpp11#106]
```r
> cpp_eval("cpp11::writable::logicals({FALSE})")
logical(0)

> cpp_eval("cpp11::writable::logicals({NA_LOGICAL})")
Error: negative length vectors are not allowed
Backtrace:
 1. cpp11::cpp_eval("cpp11::writable::logicals({NA_LOGICAL})")
 2. global::f() R/source.R:173:2
```

This seems to be because the `r_vector(R_xlen_t)` constructor is being chosen over the `r_vector(std::initializer_list<T>)` one. It can be fixed by explicitly passing an r_bool or a initializer list.

```r
> cpp_eval("cpp11::writable::logicals(std::initializer_list<r_bool>{FALSE})")
[1] FALSE

> cpp_eval("cpp11::writable::logicals({r_bool(FALSE)})")
[1] FALSE
```

**Comment by jimhester** [comment]
@bkietz I don't know if there is a lot we can do about this, any ideas? If not we should definitely document the behavior.

**Comment by bkietz** [comment]
`NA_LOGICAL` is the problem here since it's just an `int` and not an `Rboolean`. I think we'd fix this by redefining it, for example:

```c++
// r_bool.hpp, so anywhere r_bool is defined NA_LOGICAL will be well behaved:

#undef NA_LOGICAL
static constexpr Rboolean NA_LOGICAL = static_cast<Rboolean>(R_NaInt);
```

**Comment by jimhester** [comment]
Well not just `NA_LOGICAL`, because `FALSE` has the same problem (that is why you get a `length(0)` vector rather than a length 1 vector with value `FALSE` and `TRUE` only 'works' because it creates a length 1 vector which happens to have a default value of `TRUE`.

**Comment by jimhester** [comment]
Interestingly this all works correctly with gcc-10, but not with clang.

**Comment by jimhester** [comment]
I think this may be a case of this (https://stackoverflow.com/a/38966560/2055486)

**Comment by jimhester** [comment]
As this seems to be an issue only with clang and it seems the C++ spec has been updated to clarify this issue (in favor of gcc's behavior) I think we can just document it for now.
