### ISSUE TITLE
Add PACKAGE="<package name>" to .Call()

### ISSUE THREAD

**Issue by billdenney** [r-lib/cpp11#111]
I have an issue with the `systemfonts` package that appears likely to do with the order that packages are loaded (though I'm not certain).  It is fixed by adding `PACKAGE="systemfonts"` to the `.Call()` function call (https://github.com/r-lib/systemfonts/issues/53#issuecomment-699160357).  

At least in this scenario, it would be helpful if at the end of every `.Call()` the `PACKAGE="<package name>"` were added.  I'm not familiar enough with `.Call()` to know if that would ever be a bad idea.

**Comment by jimhester** [comment]
We actually had included this feature previously, but was inadvertently disabled in a refactoring.

**Comment by billdenney** [comment]
Thanks!
