### ISSUE TITLE
Add C macro for exporting symbols

### ISSUE THREAD

**Issue by xhochy** [r-lib/cpp11#115]
Currently the code generated by `cpp11` assumes that all functions are exported in the generated shared object. (i.e. `nm <shared-object>` reports a ` T ` for these functions). In some cases, it would be nice to limit the exported functions by using `-fvisibility=hidden`. When using an MSVC-based toolchain, you actually need to export all functions explicitly.

This might be as simple as reusing R's own macro `attribute_visible`. This doesn't have support for (clang-on-)MSVC yet but I'll probably try and contribute that.

**Comment by jimhester** [comment]
Sounds good, does R compile on the MSVC toolchain? I have not heard of anyone successfully doing that.

**Comment by xhochy** [comment]
> Sounds good, does R compile on the MSVC toolchain? I have not heard of anyone successfully doing that.

No, it doesn't but you can use clang-with-MSVC to build R packages. That is what we're using to build the R arrow package with the same C++ library as the Python Arrow one is using, for reference this is the PR in Arrow itself that does the black magic: https://github.com/apache/arrow/pull/8371

In the end it was sufficient to export the `R_init_*` function.

**Comment by jimhester** [comment]
Ok, as you have a workaround I will close this for now, we can re-open if needed in the future.
