### ISSUE TITLE
Confusing Name

### ISSUE THREAD

**Issue by waynelapierre** [r-lib/cpp11#120]
The package name cpp11 seems really confusing to me. Now we have C++ 20, does that mean there will be another package called cpp20?

**Comment by jimhester** [comment]
Sorry it is confusing to your.

We spent a long time considering names and this is the compromise we decided on.

Yes, it is possible there would be a cpp20, but it seems unlikely to be soon, as compiler support for C++20 wouldn't be widely available for 5-10 years from now.
