### ISSUE TITLE
Output a more useful error message if you don't register a function

### ISSUE THREAD

**Issue by jimhester** [r-lib/cpp11#127]
Right now you get 

```
Error: Can't subset columns that don't exist.
x Columns `name`, `return_type`, and `args` don't exist.
```

Which is not very helpful.

**Comment by sbearrows** [comment]
I tried recreating the error using `devtools::load_all()` in an R package by removing cpp11 decorators but I was still only able to recreate it when the content between `[[]]` was not `cpp11::register` (ex `[[cpp11:register]]`, `[[cpp11::egister]]`, etc). If there are no decorators it doesn't give any error. If there is at least one other function with the correct decorator (so one with the correct decorator and one with the incorrect decorator) the compiler gives an error that is fairly informative. I'll move ahead with the solution we discussed earlier!
