### ISSUE TITLE
Feature request : r_vector shrink_to_fit

### ISSUE THREAD

**Issue by meztez** [r-lib/cpp11#128]
If the list capacity is greater the number of elements added to a list (because of the way reserve works). A list with padded null element can be returned to R.

std::vector has a shrink_to_fit method, could it be feasible to have a similar method?

Thank you

**Comment by jimhester** [comment]
This is actually seems to be a bug when converting writable classes to read only classes. Other conversions correctly fix the length.

``` r
cpp11::cpp_function(code = 'SEXP shrink_to_fit() {
  writable::integers foo;
  foo.push_back(1);
  foo.push_back(2);
  foo.push_back(3);
  return foo;
}')

cpp11::cpp_function(code = 'integers shrink_to_fit2() {
  writable::integers foo;
  foo.push_back(1);
  foo.push_back(2);
  foo.push_back(3);
  return foo;
}')

cpp11::cpp_function(code = 'writable::integers shrink_to_fit3() {
  writable::integers foo;
  foo.push_back(1);
  foo.push_back(2);
  foo.push_back(3);
  return foo;
}')

shrink_to_fit()
#> [1] 1 2 3
shrink_to_fit2()
#> [1]  1  2  3 NA
shrink_to_fit3()
#> [1] 1 2 3
```

<sup>Created on 2020-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by meztez** [comment]
I did a 
```cpp
  cpp11::writable::raws ipc_stream;

  //...
  // Remove extra allocation
  ipc_stream.resize(ipc_stream.size());
```

Seems to take care of it. Thanks.
