### ISSUE TITLE
Operator for writable::string element -> std::string

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/cpp11#129]
It seems like we can do:

```cpp
cpp11::writable::strings x({"foo", "bar"});
cpp11::r_string elt = x[0];
std::string elt2 = elt;
```

but not:

```cpp
cpp11::writable::strings x({"foo", "bar"});
std::string elt = x[0];
```

Is that asking for too much?

Related code location:
https://github.com/r-lib/cpp11/blob/5b17608fe3074150fb0926d886f70f70530be77a/inst/include/cpp11/strings.hpp#L59-L63

**Comment by jimhester** [comment]
You can use `std::string elt(x[0])`. Assignment is not the same as copy construction.

**Comment by DavisVaughan** [comment]
<img width="596" alt="Screen Shot 2020-11-18 at 9 55 37 AM" src="https://user-images.githubusercontent.com/19150088/99546264-4251a180-2984-11eb-92e8-09b25274ce8a.png">

Hmm - does this have something to do with `zone_standard[0]` returning a proxy?

**Comment by jimhester** [comment]
Yeah it seems to be an issue with the writable versions. e.g. this works as expected

```r
cpp11::cpp_function('
  #include <string>
  std::string foo() {
  cpp11::writable::strings x({"foo", "bar"});
  cpp11::strings y(x);
  std::string elt = y[0];
  return elt;
}')
```

**Comment by jimhester** [comment]
So the issue is C++ does not allow two implicit casts. So you need to do the first one explicitly, from a proxy to a r_string. e.g.

``` r
cpp11::cpp_function('std::string foo() {
  cpp11::writable::strings x({"foo", "bar"});
  std::string elt = r_string(x[0]);
  return elt;
}')

foo()
#> [1] "foo"
```

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
```cpp
std::string elt = r_string(x[0]);
```

I didn't realize I could wrap it in one line like that, so that's pretty nice

**Comment by DavisVaughan** [comment]
The alternative here seems good enough for me
