### ISSUE TITLE
Name clash with `std::vector`

### ISSUE THREAD

**Issue by lionel-** [r-lib/cpp11#13]
I find it a bit confusing to read code with a templated class called `vector` that is not `std::vector`. How about `cpp11::r_vector<>`?

**Comment by jimhester** [comment]
This is by design, I don't think it is a problem

**Comment by artemklevtsov** [comment]
Aliases could be useful too:
```cpp
using rcpp = cpp11;
using rcpp_w = cpp1::writable;
```

**Comment by lionel-** [comment]
If it's only internal it's not that big a deal I guess. But I still think important class names should be unique even with the namespaces, otherwise reading code requires context switching.

**Comment by jimhester** [comment]
The internal name does come up in error messages, even though the typedef is also shown e.g. 

```
no known conversion from 'cpp11::writable::list' (aka 'vector<SEXPREC *>') 
```

So I think it might be worth renaming to `r_vector` to make that case more clear.
