### ISSUE TITLE
Can't seem to overwrite elements of a writable list_of

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/cpp11#131]
``` r
cpp11::cpp_source(
  code = '
  #include "cpp11/integers.hpp";
  #include "cpp11/list_of.hpp";
  
  [[cpp11::register]]
  cpp11::writable::list_of<cpp11::writable::integers> test() {
    cpp11::writable::integers x{1, 2};
    cpp11::writable::integers y{3, 4};
    cpp11::writable::list_of<cpp11::writable::integers> out({x});
    out[0] = y;
    return out;
  }
')

test()
#> [[1]]
#> [1] 1 2
```

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jimhester** [comment]
Another case of https://github.com/r-lib/cpp11/issues/129#issuecomment-730415040

**Comment by jimhester** [comment]
Thank you for opening the issue and for supplying a reproducible example, it is a big help!

This should now be fixed and work how you were expecting.
