### ISSUE TITLE
Can't automatically convert attribute proxy to cpp11::sexp

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/cpp11#132]
Since we can convert an attribute proxy to a SEXP, I was expecting to also be able to convert to a cpp11::sexp. Is that reasonable?

``` r
cpp11::cpp_source(
  code = '
  #include "cpp11/integers.hpp"
  
  [[cpp11::register]]
  cpp11::sexp test() {
    cpp11::writable::integers x{1, 2};
    SEXP names = x.attr("names");
    return names;
  }
')

test()
#> NULL

# wont compile
cpp11::cpp_source(
  code = '
  #include "cpp11/integers.hpp"
  
  [[cpp11::register]]
  cpp11::sexp test() {
    cpp11::writable::integers x{1, 2};
    cpp11::sexp names = x.attr("names");
    return names;
  }
')
#> Error in dyn.load(shared_lib, local = TRUE, now = TRUE): unable to load shared object '/var/folders/41/qx_9ygp112nfysdfgxcssgwc0000gn/T//Rtmp1XUnr9/file3dbae619bda/src/code_1.so':
#>   dlopen(/var/folders/41/qx_9ygp112nfysdfgxcssgwc0000gn/T//Rtmp1XUnr9/file3dbae619bda/src/code_1.so, 6): image not found
```

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<img width="524" alt="Screen Shot 2020-11-18 at 3 28 52 PM" src="https://user-images.githubusercontent.com/19150088/99584698-4e088c80-29b3-11eb-9a20-685ab695f1ff.png">

**Comment by jimhester** [comment]
These are all similar issues, basically C++ only allows you to do one implicit conversion. e.g. you can go from a attribute proxy to a SEXP implictly, but you can't to two implicit conversions, e.g. a `SEXP` and then a `sexp`. You have to explicitly do at least one of the casts. e.g.

```r
cpp11::cpp_function('cpp11::sexp test() {
  cpp11::writable::integers x{1, 2};
  cpp11::sexp names = SEXP(x.attr("names"));
  return names;
}')
```

**Comment by DavisVaughan** [comment]
Interesting, thanks for explaining!

**Comment by jimhester** [comment]
I am sympathetic to this and it would be nicer to add implicit conversions between the attribute and sexp, it is slightly tricky because of mutual class definitions however.
