### ISSUE TITLE
Is this package abandoned?

### ISSUE THREAD

**Issue by waynelapierre** [r-lib/cpp11#136]
I found two strange issues when using the cpp11 package. First, the cpp file name cannot contain any numbers for it to get sourced. For example, when file.cpp works, file1.cpp won't. Second, the cpp file cannot contain any comments for it to get sourced. 

These two strange issues make it almost impossible to use this package. I would like to understand if this package is abandoned.

**Comment by jimhester** [comment]
Neither of these things seem true...

``` r
writeLines("
  #include <cpp11.hpp>

  /* a comment */
  [[cpp11::register]]
  bool does_cpp11_work() {
    return true;
  }
  ",
  "file1.cpp")
cpp11::cpp_source(file = "file1.cpp")

does_cpp11_work()
#> [1] TRUE
```

<sup>Created on 2020-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by waynelapierre** [comment]
This simple cpp code cannot be sourced:

```
#include <cmath>
#include <cpp11.hpp>
using namespace std;
using namespace cpp11;

double normcdf(double x)
{
  return 0.5*erfc(-x/sqrt(2)); 
}

[[cpp11::register]]
double blsprc(int type,  //flag
              double s, //underlying
              double k, //strike                                       
              double d, //dividend yield
              double r, //risk free rate
              double tau, //maturity 
              double sigma)  
{
  double d1 = (log(s/k) + (r - d + 0.5*pow(sigma, 2))*tau)/(sigma*sqrt(tau));
  double d2 = d1 - sigma*sqrt(tau);
  
  switch(type)
  {
  case 1: return s*exp(-d*tau)*normcdf(d1) - k*exp(-r*tau)*normcdf(d2);
  case 2: return -s*exp(-d*tau)*normcdf(-d1) + k*exp(-r*tau)*normcdf(-d2);
  default: return NAN; 
  }
}



```

**Comment by jimhester** [comment]
The [decor](https://github.com/r-lib/decor) package which cpp11 uses does not handle comments intermixed between arguments.
