### ISSUE TITLE
String insertion is incredibly slow vs `SET_STRING_ELT()`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/cpp11#137]
Not a bug report, per se, but this was slow enough to make me shy away from using the nice cpp11 syntax of `out[i] = string` for now.

``` r
cpp11::cpp_function('
  cpp11::writable::strings insert_cpp11() {
    cpp11::writable::strings out(1000000);
    
    for (int i = 0; i < 1000000; ++i) {
      out[i] = "foobar";
    }
    
    return out;
  }
')

cpp11::cpp_function('
  cpp11::writable::strings insert_r() {
    cpp11::writable::strings out(1000000);
    
    for (int i = 0; i < 1000000; ++i) {
      SET_STRING_ELT(out, i, Rf_mkCharCE("foobar", CE_UTF8));
    }
    
    return out;
  }
')


bench::mark(insert_cpp11(), insert_r())
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 x 6
#>   expression          min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>     <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 insert_cpp11()     1.3s     1.3s     0.771    7.63MB     1.54
#> 2 insert_r()       22.2ms   24.2ms    32.9      7.63MB    11.6
```

<sup>Created on 2020-12-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

A quick look at Instruments seems to suggest that 95% of the time is `setjmp()` calls?

**Comment by DavisVaughan** [comment]
I guess this is because of the unwind_protect wrapper

https://github.com/r-lib/cpp11/blob/f30961521a39a8a3a5b5a53173a57b408e133b4f/inst/include/cpp11/strings.hpp#L52-L57

**Comment by jimhester** [comment]
If you are doing the latter you need to still wrap it in `unwind_protect()` outside the for loop.
