### ISSUE TITLE
Documentation wishlist

### ISSUE THREAD

**Issue by wch** [r-lib/cpp11#140]
I just started converting [websocket](https://github.com/rstudio/websocket) to cpp11, and in the process I had a number of questions. It would be helpful if the documentation had answers for them.

- [ ] What if I want to modify a vector in place? Does `writable::ints` always make a copy, or only if there's more than one reference to the object (like R since version 3.4)?
- [ ] Are the elements of a `cpp11::integers` object `int`? Similarly, are the elements of a `cpp11::strings` object `std::string`? If not, what exactly are the elements? (This can be relevant when writing `for` loops, for example.)
- [ ] What is the type of an iterator for `doubles` and `strings`? The documentation says to just use `auto`, but I'd like to have a better understanding of what it's doing.
- [ ] How do I create a new empty list? `cpp11::list x(0)` didn't seem to work. Similarly, how do I create an empty named list?
- [ ] How do I add elements to a named list? Simply doing something like `x["y"] = as_sexp(1);` didn't work.
- [ ] How do I create a new empty environment?
- [ ] How do I assign and retrieve values in an environment? And what happens if I try to get a value that doesn't exist?
- [ ] How do retrieve (named) elements from a named vector/list?
- [ ] How can I tell whether a vector/list is named or not?
- [ ] How can I create a `cpp11:raws` from a `std::string`?
- [ ] To add `std:string` elements in a list (using bracket assignment or `push_back()`), it looks like I need to wrap things with `as_sexp`. But the same isn't true if I assign `std::string` values in an environment. Why is that, and when is `as_sexp` needed in general?
- [ ] What exactly is the relationship between a `cpp11::sexp` and a `SEXP`? I found that sometimes I can use `SEXP` but not `cpp11::sexp` (for example, when specifying the return type of a function; see examples below.)

I'm sure I'll have more questions as I keep working with cpp11, and I can add them here if that makes sense. It would be nice to have API documentation and examples for the various types.

**Comment by wch** [comment]
Thanks for the answers! I do have more questions about them though.

*****

> > What if I want to modify a vector in place? Does writable::ints always make a copy, or only if there's more than one reference to the object (like R since version 3.4)?
> 
> `writable::integers()` will always makes a copy, but it has a move constructor, so if you have `SEXP x` you can use `cpp11::writable::integers(std::move(x))` and it will not copy the data.

Is there a way to make this work if the function takes a parameter that is a `cpp11::writable::integers`, or `cpp11::integers`, or does it have to take a `SEXP`?

*****

> > What is the type of an iterator for doubles and strings? The documentation says to just use auto, but I'd like to have a better understanding of what it's doing.
> 
> The iterators are internal classes in the vectors, so the type of the iterator is `cpp11::doubles::iterator` or `cpp11::writable::doubles::iterator` etc.

So when these iterators are dereferenced, they return an `int`, `double`, `r_string`, etc?

*****

> > How do I assign and retrieve values in an environment? And what happens if I try to get a value that doesn't exist?
> 
> ```c++
> my_env["foo"] = 1;
> my_env["foo"] == 1;
> 
> my_env["bar"] == R_UnboundValue;
> ```

Thanks, although the comparison results in a compile error:

```R
cpp11::cpp_function(code = '
  bool fn(cpp11::environment my_env) {
    my_env["foo"] = 1;
    return my_env["foo"] == 1;
  }', quiet = F)
#> /private/var/folders/vd/0_g4hj6d7kq_fw5gd_r0ml5w0000gn/T/Rtmpd51E4a/filec591713509f0/src/code_14.cpp:8:26: error: invalid operands to binary expression ('cpp11::environment::proxy' and 'int')
#>     return my_env["foo"] == 1;
#>            ~~~~~~~~~~~~~ ^  ~
```

If I change it to `return my_env["foo"] == as_sexp(1)`, then it compiles, but when I run `fn(new.env())`, it returns `FALSE`. Wrapping it in `cpp11:integers(1)` results in a compile error.

*****

Another question about returning general (untyped) R objects from a function. It looks like I can have a function return `SEXP`, but not `cpp11:sexp`:

For example, this works:

```R
cpp11::cpp_function(code = '
  SEXP fn(cpp11::environment my_env) {
    my_env["foo"] = 1;
    return my_env["foo"];
  }', quiet = F)
```

But if the return is a `cpp11::sexp`, it returns `NULL` and gives a warning:

```R
cpp11::cpp_function(code = '
  cpp11::sexp fn(cpp11::environment my_env) {
    my_env["foo"] = 1;
    return my_env["foo"];
  }', quiet = F)
fn(new.env())
#> NULL
#> Warning message:
#> In .Call("_code_17_fn", my_env, PACKAGE = "code_17") :
#>   converting NULL pointer to R NULL
```

Is that expected?

*****

> > How can I create a cpp11:raws from a std::string?
> 
> push back the contents individually, but we should probably write a conversion function to do this more efficiently.
> 
> ```r
> cpp11::cpp_source(code = '#include <cpp11.hpp>
>   [[cpp11::register]]
>   cpp11::raws fn() {
>     std::string x("hi");
>     cpp11::writable::raws out;
>     for (auto c : x) {
>       out.push_back(c);
>     }
>     return out;
>   }')
> fn()
> #> [1] 68 69
> ```

FWIW, this doesn't quite seem to work. It includes some junk in the output.

```R
cpp11::cpp_function(code = '
cpp11::raws to_raw(const std::string x) {
  cpp11::writable::raws out(x.size());
  for (auto c : x) {
    out.push_back(c);
  }
  return out;
}', quiet = F)
to_raw("abcd")
#> [1] 01 00 00 00 61 62 63 64
to_raw("abcd")
#> [1] c0 ee 80 66 61 62 63 64
to_raw("abcd")
#> [1] 67 72 65 79 61 62 63 64
to_raw("abcd")
#> [1] 88 50 81 67 61 62 63 64
to_raw("abcd")
#> [1] 01 00 00 00 61 62 63 64
```

The same happens if `x` is defined within the function, instead of pass into it.

**Comment by jimhester** [comment]
> Is there a way to make this work if the function takes a parameter that is a cpp11::writable::integers, or cpp11::integers, or does it have to take a SEXP?

Those types implicitly coerce to SEXP, it will already work. But there are basically very few times you should ever do this, and I generally don't want to make it easy to do.

> So when these iterators are dereferenced, they return an int, double, r_string, etc?

For the read-only classes yes, for the writable ones they return a proxy object that supports assignment and automatically dereferences to the underlying type when dereferenced.

> comparison results in a compile error:

you would need to convert the sexp result to an integer before the comparison. e.g. `as_cpp<int>(my_env["foo"]) == 1`

> then it compiles, but when I run fn(new.env()), it returns FALSE

This is a bug with single element logicals, the wrong constructor is being called, it is basically the same problem as https://github.com/r-lib/cpp11/issues/106. This is currently documented, but it is worse than I realized in that issue, as you run into it for any single bool result also.

> It looks like I can have a function return SEXP, but not cpp11:sexp

I never considered someone thinking to return a `cpp11::sexp` from a registered function. But we can add it.

> this doesn't quite seem to work. It includes some junk in the output.

That is due to a bug https://github.com/r-lib/cpp11/commit/505e1c55934b861d93345c8ac2199dc20541533a, when converting from a writable::raws to a raws, it is fixed in the devel version of cpp11, but not yet on CRAN. If you use a `cpp11::writable::raws` or a `SEXP` as the return value (or the devel version of cpp11) you won't see this behavior.

**Comment by sbearrows** [comment]
Added most of these to the FAQ!

**Comment by wch** [comment]
Thanks!
