### ISSUE TITLE
Document the need to use brace initialiazation when returning `cpp11::writable::logicals()`.

### ISSUE THREAD

**Issue by jimhester** [r-lib/cpp11#142]
``` r
cpp11::cpp_function(code = '
  cpp11::writable::logicals fn() {
    return false;
  }')
fn()
#> logical(0)

cpp11::cpp_function(code = '
  cpp11::writable::logicals fn2() {
    return {false};
  }')
fn2()
#> FALSE
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
This happens because the first case uses the `R_xlen_t size` constructor and the second uses the `std::initializer_list<>()` constructor.

**Comment by sbearrows** [comment]
For the FAQ vignette should I add the explanation in your second comment of why this happens or just the example of how to return cpp11::writable::logicals() objects?

**Comment by sbearrows** [comment]
Added to faq
