### ISSUE TITLE
int64_t can overflow in as_sexp

### ISSUE THREAD

**Issue by nealrichardson** [r-lib/cpp11#145]
I encountered this trying to print some memory statistics in https://github.com/apache/arrow/pull/9170.

Minimal example: 

```r
cpp11::cpp_source(code = '
#include <cpp11.hpp>

[[cpp11::register]]
int64_t fun(int extra) {
  // This is max int32
  int64_t a = 2147483647;
  return a + extra;
}
')
fun(0)
## [1] 2147483647
fun(999)
## [1] -2147482650
```

How should this be handled? If the `int64_t` is above max int, should `as_sexp` convert it to `double`? Should this handling be in `cpp11` or in my code? (I tried defining an `as_sexp` for `int64_t` to test this out but it exceeds my C++ chops.)

cc @bkietz

**Comment by jimhester** [comment]
I think you will just need to return a double from your function if you want to be able to store values that cannot be stored in Rs 32 bit integers.

**Comment by nealrichardson** [comment]
Fair enough, I can return the ones that I expect to exceed 32 bits as `double`. Thanks!
