### ISSUE TITLE
Parse C++ Roxygen blocks

### ISSUE THREAD

**Issue by mpadge** [r-lib/cpp11#147]
This is currently not done at all, and so any packages which export C++ fns straight to R will not inherit the documentation. The `Rcpp` parsing of Roxygen blocks is pretty straightforward. Blocks are identified [here](https://github.com/RcppCore/Rcpp/blob/98173e5cb72b124580723b7c0dd9669127e2b3ef/src/attributes.cpp#L3025-L3042) and simply pushed back onto an output vector [here](https://github.com/RcppCore/Rcpp/blob/98173e5cb72b124580723b7c0dd9669127e2b3ef/src/attributes.cpp#L1219-L1228), which is ultimately dumped straight to `R/RcppExports.R`. Having the ability to parse C++ Roxygen blocks in `cpp11` is pretty important - any chance of an easy implementation?

Further motivation: It's impossible to use custom roclets intended to apply to `src/` code without this functionality.

**Comment by jimhester** [comment]
I made a conscious decision not to support this, in practice it is pretty rare that we write C++ functions without any accompanying R code, so I don't feel the added complexity worth it.

If we were going to do this I think it would be as a custom roxygen roclet that runs on the `src/` code completely independent of cpp11 registration.

**Comment by mpadge** [comment]
Yeah, fair enough. That's what I've done for `Rcpp` anyway, because the `RcppExports` file does not retain the actual line numbers in `src/`, so you need a custom roclet to generate those anyway. I'll just write an additional cpp11 roclet  function to be run if a `cpp11.R` file is found. Thanks!

And to justify your decision: I checked on local CRAN mirror today, and only 2 / 16016 packages even use custom roclets (at least as retained in CRAN-redundant `Roxgen`-line of DESC files). So any likely benefit of implementing this would be relevant to a very insignificant microcosm of packages. All good!
