### ISSUE TITLE
What is a single element of writeable::strings?

### ISSUE THREAD

**Issue by mpadge** [r-lib/cpp11#150]
A single element of (readable/const) `strings` is accessible as `std::string`, but attempting same for `writable::strings` generates compilation error. This code reproduces:

```cpp
#include "cpp11.hpp"
#include <string>

using namespace cpp11;
namespace writable = cpp11::writable;

[[cpp11::register]]
void cpp_test(list df) {

    integers i = df["i"];
    doubles j = df["j"];
    strings k = df["k"];

    int i0 = i[0];
    double j0 = j[0];
    std::string k0 = k[0]; // accessible as expected

    writable::integers iw = df["i"];
    writable::doubles jw = df["j"];
    writable::strings kw = df["k"];

    i0 = iw[0];
    j0 = jw[0];
    //k0 = kw[0]; <- DOES NOT WORK!!
}
```

Uncommenting that last line gives "no known conversion from `cpp11::writable::r_vector<cpp11::r_string>::proxy` to `const std::__cxx11::basic_string<char>`".

**Comment by jimhester** [comment]
See https://github.com/r-lib/cpp11/issues/129#issuecomment-730415040

**Comment by mpadge** [comment]
Ah, thanks, and as @DavisVaughan says:

> The alternative here seems good enough for me

... good enough for me too.
