### ISSUE TITLE
Consider putting the precious list in the package namespace rather than a global option.

### ISSUE THREAD

**Issue by jimhester** [r-lib/cpp11#151]
This would potentially allow easier debugging when tracking down memory issues.

Basically you would need to add a call to a function in `.onLoad()` that initializes the precious list for that package.

For rmarkdown use cases we would use the cpp11 namespace to hold the list.

**Comment by DavisVaughan** [comment]
https://github.com/r-lib/cpp11/pull/331 moved us towards one preserve list per compilation unit, and removed our reliance on a global option, which had caused issues over the years (in particular, if we ever change the structure of it, we can completely bork anyone who vendored cpp11 and still used the old structure)

https://github.com/r-lib/cpp11/pull/364 moves us towards one preserve list per package
