### ISSUE TITLE
Please consider documenting the difference between this and rcpp

### ISSUE THREAD

**Issue by kkweon** [r-lib/cpp11#152]
It has "how to migrate from Rcpp" but doesn't tell why I may consider migrating.

For references, I have read

- https://cpp11.r-lib.org/articles/motivations.html
- https://cpp11.r-lib.org/articles/converting.html

But I'm still not sure on "why" part.
Rcpp also supports modern C++.

Maybe show an example where cpp11 shines better than Rcpp.

Especially make it highly visible like putting onto README and any index page as this is the first thing people will wonder.

**Comment by jimhester** [comment]
That is what https://github.com/r-lib/cpp11#motivations and the motivations vignette is doing.

**Comment by kkweon** [comment]
Ok, thank you.
