### ISSUE TITLE
Vignette motivations.Rmd fails to build

### ISSUE THREAD

**Issue by jeroen** [r-lib/cpp11#161]
See: https://github.com/r-universe/r-lib/runs/2240745365?check_suite_focus=true

```
--- re-building ‘motivations.Rmd’ using rmarkdown
Quitting from lines 100-110 (motivations.Rmd) 
Error: processing vignette 'motivations.Rmd' failed with diagnostics:
there is no package called 'Rcpp'
--- failed re-building ‘motivations.Rmd’
```

I think what happened is that previously Rcpp was implicitly installed via one of your Suggests dependencies, but it probably is no longer a dependency anywhere.

**Comment by jimhester** [comment]
Thanks, should be fixed by https://github.com/r-lib/cpp11/commit/5892862b77b59e4a443e4c58320e5496530e9a30 then
