### ISSUE TITLE
writable::list() creates a NULL

### ISSUE THREAD

**Issue by hadley** [r-lib/cpp11#166]
``` r
cpp11::cpp_eval("cpp11::writable::list()")
#> NULL
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jimhester** [comment]
This is really the crux of it, the error is coming from the cpp11::list constructor.

```r
cpp11::list foo(cpp11::writable::list())
```

We could have a more informative error message when a `cpp11::writable::list()` is passed and the SEXP is `R_NilValue`, this indicates trying to create a view on a default constructed list.
