### ISSUE TITLE
How to embed R into a C++ program with cpp11 (similar to RInside)

### ISSUE THREAD

**Issue by yimyom** [r-lib/cpp11#167]
I would like to embed R into a C++ program to achieve the following. For the context, I already made it work for Python with pybind11 and now I need to make it work in R too:

1. I want to use cpp11 instead of Rcpp (because of all the features you've listed that cpp11 has),
2. in R, the user can create or inherit a R class from a C++ class and implement it completely in R. Think about the C++ being the interface and the R class the implementation (I've made it work for python with pybind11 and Boost.Python by the way)
3. my C++ code, which is the main program, will start the R interpreter, instantiate the user's class given in a separate file at runtime, and then make calls to the methods of the R class from C++ and get some results.
4. I want to use cpp11 to provide a wrapper to classes and functions living inside the C++ code, so that the user can access algorithms and data I provide in C++. So in essence, C++ can call R and R can call C++.
4. I've read https://cpp11.r-lib.org/articles/converting.html#calling-r-functions-from-c- already

Questions:

1. is is possible to achieve a similar result with cpp11 and how?
2. should I use RInside instead?
3. Can RInside work well with cpp11?

**Comment by jimhester** [comment]
Thanks for filing this issue! Unfortunately, robustly supporting this use case is out of scope for the cpp11 package.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

I would suggest you use RInside to handle this use case. Though it is possible to use cpp11 and Rcpp in the same project, as both packages work with `SEXP` vectors.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
