### ISSUE TITLE
Need to set locale before calling `package_native_routine_registration_skeleton()`

### ISSUE THREAD

**Issue by hadley** [r-lib/cpp11#171]
Since `tools:::native_routine_registration_db_from_ff_call_db()` calls `order()`, leading to spurious diffs like https://github.com/r-lib/roxygen2/commit/e8cd3131f22db8256168f0b40adcd58144b2f794

**Comment by jimhester** [comment]
I think the best way to fix this would be to temporarily use C collation with `withr::with_collate()` when calling `tools::package_native_routine_registration_skeleton()`

https://github.com/r-lib/cpp11/blob/41232a807371418253facfa7d0a7f75c74e0bcc6/R/register.R#L248-L253
