### ISSUE TITLE
Add cpp11 talk to the README

### ISSUE THREAD

**Issue by jimhester** [r-lib/cpp11#172]
The talk is at here, https://youtu.be/_kq0N0FNIjA, the slides are at https://speakerdeck.com/jimhester/cpp11-welding-r-and-c-plus-plus.

An example at of doing this in vroom is at https://github.com/r-lib/vroom/blob/8af8e789a14558e7ac3f6e6593f2db388727344a/README.Rmd#L162

**Comment by sbearrows** [comment]
Submitted a pull request with links in the readme

**Comment by jimhester** [comment]
Btw you can add 'fixes #172' to the bottom of your commit message and the corresponding issue will automatically be closed when the pull request is merged.
