### ISSUE TITLE
`false` not currently working for Windows and Ubuntu platforms

### ISSUE THREAD

**Issue by sbearrows** [r-lib/cpp11#187]
Currently `false` is not working for certain versions of Windows and all versions of Ubuntu on `R CMD check`

**Comment by jimhester** [comment]
Might need a new template specialization for `initializer_list<bool>`
https://github.com/r-lib/cpp11/blob/fe9850f4a1874a3769a3e4f7ac4221eec6adf310/inst/include/cpp11/logicals.hpp#L76-L84
