### ISSUE TITLE
rename `[[cpp11::export]]`

### ISSUE THREAD

**Issue by jimhester** [r-lib/cpp11#20]
export is a nice term, but is unfortunately somewhat confusing due to roxygen2 and NAMESPACE using export for exported functions.

`[[cpp11::use_from_r]]` seems to match the intent of the attribute best and is nicely self documenting.

**Comment by DavisVaughan** [comment]
@lionel- and I also sometimes use the equivalent of `[[cpp11::register]]` in vctrs C code to indicate that this function is going to be registered to be called from the R side. It isn't as self-documenting, but it is another option

**Comment by jimhester** [comment]
Sure, we can use `[[cpp11::register]]`

**Comment by jimhester** [comment]
We now use `cpp11::register`
