### ISSUE TITLE
#pragma once is non-standard

### ISSUE THREAD

**Issue by kevinushey** [r-lib/cpp11#22]
Although it's _probably_ supported on all compilers used on CRAN (even Solaris IIUC) it's probably better to stick to the standard include guards.

**Comment by jimhester** [comment]
While it is not officially standard, it is de-facto standard, basically every compiler in use today supports it (https://en.wikipedia.org/wiki/Pragma_once#Portability) and it is less error prone than include guards, I used it here deliberately.

As other points of reference I have been using '#pragma once' in odbc, fs, vroom etc. for multiple years without anyone having trouble with compiler support.

**Comment by kevinushey** [comment]
Fair enough!
