### ISSUE TITLE
Compile error on R 3.3 with dev version

### ISSUE THREAD

**Issue by nealrichardson** [r-lib/cpp11#226]
Like #225, when we built `arrow` with the master branch of `cpp11`, there is a compile error on R 3.3:

```
../inst/include/cpp11/r_vector.hpp: In function ‘SEXPREC* cpp11::writable::truncate(SEXP, R_xlen_t, R_xlen_t)’:
../inst/include/cpp11/r_vector.hpp:889:30: error: ‘length_’ was not declared in this scope
   x = safe[Rf_lengthgets](x, length_);
                              ^~~~~~~
../inst/include/cpp11/r_vector.hpp:889:30: note: suggested alternative: ‘length’
   x = safe[Rf_lengthgets](x, length_);
                              ^~~~~~~
                              length
```

See https://github.com/ursacomputing/crossbow/runs/3302757244?check_suite_focus=true#step:8:1992

It looks like a typo perhaps: https://github.com/r-lib/cpp11/compare/v0.3.1...master#diff-65ceb5633686ca7a39f13ea1af039ba5b7bbc7bd225ca4eedbe181cf097ab0e6R887

**Comment by jimhester** [comment]
Thanks, we no longer 'officially' support R 3.3, which is why R 3.3. was not in the CI matrix, but it definitely looks like a typo.
