### ISSUE TITLE
should package::operator[] allow for return of non-function objects?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/cpp11#23]
E.g. here:

https://github.com/r-lib/cpp11/blob/d4fc65050293a16a402ec6d038cbe1e2451b431a/inst/include/cpp11/function.hpp#L54-L56

Perhaps this could return a proxy object that is convertible to the user-requested type (`function`, `SEXP`, and so on)?

**Comment by jimhester** [comment]
One advantage of returning a function is you can immediately use it with `operator()` to perform a function call.

There is a different interface for environments that you one could use instead which has an interface more of what you were thinking of. It could be used to get a non-function object out of a namespace (https://github.com/r-lib/cpp11/blob/d162014a1f90eb2cdc5646501504a5b2fc05f4e4/inst/include/cpp11/environment.hpp#L41).

**Comment by jimhester** [comment]
I think for now we will leave the API as is, if we need to provide more genericity in the future we can revisit.
