### ISSUE TITLE
avoid potential null deref in as_cpp

### ISSUE THREAD

**Issue by kevinushey** [r-lib/cpp11#26]
Looking here:

https://github.com/r-lib/cpp11/blob/cf7391b1d010b6ed02e1e6d8f541e04183114daa/inst/include/cpp11/as.hpp#L109-L115

If an error occurs during translation, `c_p` will remain as a `nullptr` and then the attempt to access the zero-th element will likely crash.

**Comment by jimhester** [comment]
If an R error occurs in L112 the unwind protect will throw a C++ exception, so L113 wouldn't run in that case.
