### ISSUE TITLE
RNG Scope?

### ISSUE THREAD

**Issue by coatless** [r-lib/cpp11#27]
Any thoughts on ensuring the correct RNG functionality with the `Rmath` library? 

For instance, if we create a `cpp11` function that interfaces with `Rf_norm()`: 

```r
cpp11::cpp_source(
    code = '
#include "cpp11/doubles.hpp"
#include "R.h"
#include "Rmath.h"

[[cpp11::register]]
double rng_cpp() {
  double x = Rf_rnorm(0, 1);
  return x;
}

[[cpp11::register]]
double rng_explicit_state_cpp() {
  GetRNGstate();
  double x = Rf_rnorm(0, 1);
  PutRNGstate();
  return x;
}', quiet = FALSE)
```

The subsequent running of the versions between _C++_ and _R_ produce the same result without a seed being re-set.

```r
set.seed(3161611)
rng_cpp()
#> [1] -0.9325398
rnorm(1)
#> [1] -0.9325398
```

Under the second function with an explicit Get/Put state call the desired results are achieved: 

```r
set.seed(3161611)
rng_explicit_state_cpp()
#> [1] -0.9325398
rnorm(1)
#> [1] 0.8282708
```

From looking at exported code it seems like there is no wrapping of C++ calls with `GetRNGstate()`/`PutRNGstate()`. Perhaps this should be added to the converting documents or addressed during code generation?

**Comment by jimhester** [comment]
Generally I think if you want this you should put the requisite calls to `GetRNGstate()` in your code.
