### ISSUE TITLE
Clarify the necessary "move" w.r.t. `SystemRequirements: C++11`

### ISSUE THREAD

**Issue by jennybc** [r-lib/cpp11#314]
Currently cpp11's README and, therefore, home page says:

> ... add the following to your DESCRIPTION file:
>
>     LinkingTo: cpp11
>     SystemRequirements: C++11

But [as we all know too well](https://www.tidyverse.org/blog/2023/03/cran-checks-compiled-code/#note-regarding-systemrequirements-c11), CRAN is asking for packages to drop `SystemRequirements: C++11` in general.

Should this advice be changed in cpp11?

My immediate motivation for opening this issue is to do my due diligence before I modify `usethis::use_cpp11()` to stop adding `SystemRequirements: C++11` to DESCRIPTION (https://github.com/r-lib/usethis/issues/1824).

**Comment by stephematician** [comment]
As someone who just submitted their first package ... yeah, that was a weird hurdle. Would make life easier if the advice was updated.

Re some of the advice in that tidyverse blog:  I'm not sure I agree that `CXX_STD=CXX11` should be removed from `Makevars` seeing as some older compilers might not default to the standard - so it can't hurt to give them a chance. I'd prefer to leave it in, and CRAN doesn't seem to mind.

**Comment by jennybc** [comment]
Since I opened this issue, I made the executive decision for `usethis::use_cpp11()` to stop putting `C++11` in `SystemRequirements`. That is currently only the dev version of usethis, but there will be a release soon-ish.

https://github.com/r-lib/usethis/commit/4a83ded76fcd813c6846fdca0ce2d9c16e05524a

**Comment by stephematician** [comment]
Recently my package fails to build on R-devel (rhub) as the C++11 flags are not correctly set.

[literanger_0.0.1.tar.gz-63dcc0cf2ce245d0b82fc83c07bc880e.txt](https://github.com/r-lib/cpp11/files/11859404/literanger_0.0.1.tar.gz-63dcc0cf2ce245d0b82fc83c07bc880e.txt)
