### ISSUE TITLE
should cpp11 support string_view?

### ISSUE THREAD

**Issue by CreRecombinase** [r-lib/cpp11#37]
R strings seem like a pretty perfect use case for [std::string_view](https://en.cppreference.com/w/cpp/string/basic_string_view).  For compilers that don't support c++17, there are [backports available](https://github.com/martinmoene/string-view-lite).  Any interest in a pull request?

**Comment by jimhester** [comment]
I don't think it is entirely trivial to do this. First as you mentioned we would need to use compatibility library so we could use it with C++11.

Second and perhaps more importantly cpp11 uses `translateCharUT8()` to access character data from R vectors. This translates the characters to UTF-8 and (if needed) allocates memory that reclaimed at the end of the enclosing `.Call()`. If we use `string_view()` on this data and the `string_view()` outlasts the `.Call()` boundary the data will no longer be valid.

It might be that this particular case is rare enough and the benefits of string_view are substantial enough that it makes sense, I am not sure.

**Comment by jimhester** [comment]
Another pretty serious issue with using `string_view` in cpp11 is that nearly all R APIs that have `const char*` expect null terminated strings, which may not be the case with a string_view.

**Comment by CreRecombinase** [comment]
Yeah the point about possible allocation by `translateCharUTF8` totally makes sense.  I guess I was thinking of `string_view` as modeling the contents of a `CHARSXP` "as it is".  Operationally, I think of a `string_view` as 
1) non-owning 
2) cheap to copy 
3) immutable (unlike other "data" SEXP, you can't muck easily around with the contents of a `CHARSXP` in-place because of the `CHARSXP` cache. `string_view`, unlike its cousin `span`, will only give you a const pointer to its contents)
4) ["knowing" its own length](https://purrple.cat/blog/2018/03/05/strings-know-their-own-length/)

**Comment by jimhester** [comment]
Closing this issue for now, while I do think using string_view is a nice idea in theory, I don't think it really will work in practice for cpp11 due to the concerns expressed above.
