### ISSUE TITLE
Avoid trailing whitespace in generated files

### ISSUE THREAD

**Issue by richfitz** [r-lib/cpp11#38]
This package is very exciting - I'm exploring using it on a couple of projects at the moment. I've noticed that the cpp11.cpp and cpp11.R files that are created have a trailing blank line. I would create a PR to fix it, but this looks intentional (https://github.com/r-lib/cpp11/blob/0a202e50ff39064b1e66d6981e2e8a2bbc4aa50a/R/register.R#L88 and https://github.com/r-lib/cpp11/blob/0a202e50ff39064b1e66d6981e2e8a2bbc4aa50a/R/register.R#L43) - is there a reason for this or could this be dropped?

Also, how stable is the API likely to be? I recognise this is very much a work in progress, but also clearly something you've been thinking about for a bit.

**Comment by jimhester** [comment]
No reason, the trailing blank is now gone.

I don't really expect the API to change radically now, but if you are worried about it you can always vendor the headers in your package with `cpp11::cpp_vendor()` (and remove `LinkingTo: cpp11`) to ensure they don't change.
