### ISSUE TITLE
Make cpp functions visible to other packages

### ISSUE THREAD

**Issue by NicChr** [r-lib/cpp11#407]
Hello, is there a way to make my C++ functions accessible through cpp11 (or other means) to other R packages that use C/C++?

The goal is to be able to call package A's C++ functions directly in package B's C++ code though I'm not sure how to accomplish this given that much of the registration is automatically generated. 

Any help would be appreciated, thanks!

**Comment by DavisVaughan** [comment]
It is possible, though it is not at all easy, but systemfonts does this

It utilizes `[[cpp11::init]]` to register functions as "callable" at the C level
https://github.com/r-lib/systemfonts/blob/02b567086379edaca1a9b3620ad6776e6bb876a7/src/font_fallback.cpp#L78
https://github.com/r-lib/systemfonts/blob/02b567086379edaca1a9b3620ad6776e6bb876a7/src/font_fallback.h#L15

Then exposes a header file that is used by other packages
https://github.com/r-lib/systemfonts/blob/02b567086379edaca1a9b3620ad6776e6bb876a7/inst/include/systemfonts.h

For example, ragg uses it by LinkingTo systemfonts
https://github.com/r-lib/ragg/blob/6e8bfd1264dfaa36aa6f92592e13a1169986e7b9/DESCRIPTION#L35
