### ISSUE TITLE
rchk error

### ISSUE THREAD

**Issue by NicChr** [r-lib/cpp11#408]
Hi, I'm getting an rchk error and not sure if it relates to my code directly or something I can't fix on my side.
https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/fastplyr.out

Many thanks!

The error:

```{r}
Function cpp11::writable::r_vector<SEXPREC*>::reserve_data(SEXPREC*, bool, long)
  [UP] calling allocating function cpp11::writable::r_vector<SEXPREC*>::resize_names(SEXPREC*, long) with a fresh pointer (names <arg 1>) cpp11/include/cpp11/r_vector.hpp:1329
```

**Comment by pepijn-devries** [comment]
Hi there,

Has it been confirmed that this commit fixed the issue reported here? This commit is included in the latest release (0.5.1) which is also on CRAN. However, I'm still receiving similar `rchk` reports as reported here. See for instance:

https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/ProTrackR2.out
https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/adfExplorer.out

Are these issues indeed related? Should this have been fixed by https://github.com/r-lib/cpp11/pull/409? Or is this something I need to fix myself?

**Comment by jayhesselberth** [comment]
#409 doesn't appear to have fixed the rchk issue, still being flagged in several packages:

https://cloud.r-project.org/web/checks/check_results_cpp11bigwig.html
https://cran.r-project.org/web/checks/check_results_tweenr.html

**Comment by jayhesselberth** [comment]
I wonder if it should be something like:

```cpp
if (Rf_xlength(names) != size) {
  SEXP resized_names = PROTECT(resize_names(names, size));
  Rf_setAttrib(out, R_NamesSymbol, resized_names);
  UNPROTECT(1);
}
```

**Comment by pepijn-devries** [comment]
@r-lib @DavisVaughan It looks like this issue needs to be reopened?

**Comment by jwood000** [comment]
I think the error message from `rchk` is pretty telling:

> Function ... *reserve_data* ... calling allocating function ... *resize_names*

If we look at the current definition of `reserve_data` found here:

https://github.com/r-lib/cpp11/blob/2938879645f4bf6fd2905c51cb437f0318ed8da2/inst/include/cpp11/r_vector.hpp#L1321

We see the following code:

```c++
.
.
.
  // Resize names, if required
  // Protection seems needed to make rchk happy
  SEXP names = PROTECT(Rf_getAttrib(x, R_NamesSymbol));
  if (names != R_NilValue) {
    if (Rf_xlength(names) != size) {
      names = resize_names(names, size);
    }
    Rf_setAttrib(out, R_NamesSymbol, names);
  }
.
.
.
```

The problem line is `names = resize_names(names, size);`. We can rewrite the above as:

```c++
.
.
.
  // Resize names, if required
  // Protection seems needed to make rchk happy
  SEXP names = PROTECT(Rf_getAttrib(x, R_NamesSymbol));
  if (names != R_NilValue) {
    if (Rf_xlength(names) != size) {
      SEXP names_resized = PROTECT(resize_names(names, size));
      Rf_setAttrib(out, R_NamesSymbol, names_resized);
      UNPROTECT(1);
    } else {
      Rf_setAttrib(out, R_NamesSymbol, names);
    }
  }
.
.
.
```

**Comment by DavisVaughan** [comment]
From what I can tell, every listed package did the rchk run on 2024-11-21

The cpp11 release was on 2024-12-04

The full message is

```
Function cpp11::writable::r_vector<SEXPREC*>::reserve_data(SEXPREC*, bool, long)
  [UP] calling allocating function cpp11::writable::r_vector<SEXPREC*>::resize_names(SEXPREC*, long) with a fresh pointer (names <arg 1>) cpp11/include/cpp11/r_vector.hpp:1329
```

The main problem being

```
with a fresh pointer (names <arg 1>)
```

Which is why the fix protects `names`.
https://github.com/r-lib/cpp11/pull/409/files

If anyone can reproduce with CRAN cpp11 and provide an easy way for me to reproduce as well, then we can reopen. But I think CRAN just hasn't rerun rchk on these packages.

**Comment by DavisVaughan** [comment]
An exception is cpp11bigwig, run on 2025-01-09
https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/cpp11bigwig.out

```
Function cpp11::writable::r_vector<SEXPREC*>::r_vector(std::initializer_list<cpp11::named_arg>)::{lambda()#1}::operator()() const
  [UP] unprotected variable names while calling allocating function Rf_mkCharCE cpp11/include/cpp11/list.hpp:91
```

That is a different issue from the one I tried to fix. I will open a different issue for that.

**Comment by pepijn-devries** [comment]
> An exception is cpp11bigwig, run on 2025-01-09 https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/cpp11bigwig.out
> 
> ```
> Function cpp11::writable::r_vector<SEXPREC*>::r_vector(std::initializer_list<cpp11::named_arg>)::{lambda()#1}::operator()() const
>   [UP] unprotected variable names while calling allocating function Rf_mkCharCE cpp11/include/cpp11/list.hpp:91
> ```
> 
> That is a different issue from the one I tried to fix. I will open a different issue for that.

This test result is from January:

https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/adfExplorer.out

**Comment by DavisVaughan** [comment]
Yes, and that is a different issue from the original one here. I opened #445 for this.
