### ISSUE TITLE
Using iterators with matrices

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/cpp11#41]
Using iterators are great for abstraction away some of the boilerplate as outlined in https://cpp11.r-lib.org/articles/cpp11.html#using-iterators.

Is it possible to use the same framework to perform calculations in a row-wise fashion for a matrix?

**Comment by jimhester** [comment]
I added a simple forward iterator, enough to do ranged based for loops e.g. the `row_sums` implementation at 
https://github.com/r-lib/cpp11/blob/9cba5716910ef9bfca33fc119d9edd39ba2d1e4c/cpp11test/src/matrix.cpp#L70-L86

We can add additional operators in the future
