### ISSUE TITLE
Need modify in-place

### ISSUE THREAD

**Issue by renkun-ken** [r-lib/cpp11#42]
Sometimes for best performance, in-place modification is really needed. For example, if one needs a cpp11 function that in-place sorts an R vector without making a copy just like `std::sort`, or  a cpp11 functions that performs in-place winsorization for speed (because it knows that the input vector is only intermediate and could be changed to avoid more allocation). I'm wondering if there's a decent way to do so without using  `DATAPTR` from R C API?

A major point of using Rcpp is for speed but I'm wondering if modifying an R vector by reference is completely prohibited in cpp11?

**Comment by jimhester** [comment]
You can always use the C API directly, e.g. `REAL_ELT()`, `DOUBLE_ELT()` etc.
