### ISSUE TITLE
Permissive handling of integers in cpp11::integers

### ISSUE THREAD

**Issue by richfitz** [r-lib/cpp11#46]
At the moment, coersion from an R numeric scalar to an `int` works nicely - doubles are converted to integers if they are representable as integers without truncation of the decimal part. However, the same is not true of a vector of numeric values into `cpp11::integers`:

```r
cpp11::cpp_source(
  code = c(
    "#include <cpp11.hpp>",
    "[[cpp11::register]]",
    "void test(int x, cpp11::integers y) {",
    "}"))
test(1L, 1L) # works, as expected
test(1, 1L)  # works, due to the double -> int conversion
test(1L, 1)  # fails with error "Invalid input type, expected 'integer' actual 'double'"
```

The same problem impacts passing a vector of integers to a function expecting doubles:

```r
cpp11::cpp_source(
  code = c(
    "#include <cpp11.hpp>",
    "[[cpp11::register]]",
    "void test2(cpp11::doubles y) {",
    "}"))
test2(seq_len(4))
#> Error in test2(seq_len(4)) : 
#>   Invalid input type, expected 'double' actual 'integer'
```

It would be nice if it is possible to relax this as practically this requires additional wrappers to the be added in either the C++ or the R code, especially as the name of the problematic variable can't be easily found from the error message.

**Comment by jimhester** [comment]
I understand the appeal, but not doing this was a design decision.

Allowing this (as for example Rcpp does) requires checking the vector type and coercing the vector, which then copies all of the data.

I think it is in general better for package developers to be more concrete with vector types and if they do want coercions to do that when calling the functions, e.g. with `as.integer()`

**Comment by richfitz** [comment]
I understand the want to keep the package nice and lean (R6 is great to use partly because Winston is so good at rebuffing feature requests like this).

Practically though, that means that every function that accepts a vector will need to have two layers of wrapping, one that applies the coercion then the one in R/cpp11.R, as unless you're the sole creator of all inputs you can't guarantee the storage mode. That will lead to a lot of duplication across packages using this (and does not really do anything to prevent the copying - that will be necessary if the types don't agree regardless of where it happens).

Would you consider helper functions within the `cpp11` that could be used to help that, even if they're not automatically used? I've just written this somewhat icky function: https://github.com/mrc-ide/dust/blob/f4e9502b3a0c997bee43727bb252194c051442ac/inst/include/dust/interface.hpp#L248-L268 to try and help with this, but I imagine that this sort of thing will end up duplicating.

Thanks again for this package, the compilation speed, while still much longer than plain C, is making it so nice to use.

**Comment by jimhester** [comment]
Sure we could add a `as_integers()` helper in the cpp11 namespace in `as.hpp`. We probably should have an `as_doubles()` one as well.

We also might be able to use that coercion logic implicitly for `writable::integers()`. There we have to duplicate the data anyway so that cost is not as much of a concern.
