### ISSUE TITLE
LinkingTo directive with cpp_source?

### ISSUE THREAD

**Issue by thk686** [r-lib/cpp11#48]
Is there an equivalent to // [[Rcpp::depends(<pkg>)]] for cpp11? Trying to make a MRE (so not in a package) and need to link with another package for that one bit of code.

**Comment by jimhester** [comment]
No, there is not currently.

**Comment by thk686** [comment]
OK. I'll then nominate that for a feature. I have a fair bit of code that
is compiled on-the-fly and needs to link out to other libraries.

THK

**Comment by jimhester** [comment]
As of b93824 you can now use `[[cpp11::linking_to()]]` in a similar fashion as `// [[Rcpp::depends()]]` to link to third party packages.
