### ISSUE TITLE
Difficulty understanding the protection benchmarks

### ISSUE THREAD

**Issue by thk686** [r-lib/cpp11#49]
I've read [this](https://cpp11.r-lib.org/articles/motivations.html#protection) a few times and I confess I cannot make heads or tails of the results. Perhaps I'm just reading it wrong. I thought I'd mention it incase there is a bug. I'm usually adept at interpreting plots, so if its correct, perhaps there is another way to present the data?

**Comment by hadley** [comment]
I think the labels might be flipped

**Comment by thk686** [comment]
I think that's right. I'm really enjoying using the package in my latest
project, so thanks for that.

THK

**Comment by jimhester** [comment]
It is my mistake, I had to IFDEF the Rcpp version of that benchmark out to avoid a rchk false positive, but I forgot to set the flag when I re-ran the benchmark code. So the Rcpp version is essentially an empty function.
