### ISSUE TITLE
as_cpp<Enum>

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/cpp11#52]
It would be nice to have some mechanism to move enums back and forth between R and C++. I'm not sure what `as_sexp()` would do but `as_cpp<Enum>` could be: 

```cpp
namespace cpp11 {

template <typename E>
typename std::enable_if<std::is_enum<E>::value, E>::type as_cpp(SEXP from) {
  return E(cpp11::as_cpp<typename std::underlying_type<E>::type>(from));
}

}
```

If this is of interest, I'll polish and make it a proper pull request. 

In `Rcpp` we had to use the `RCPP_EXPOSED_ENUM_NODECL` macro to declare each enum we wished to expose, manually, which sets some templates for `Rcpp::as<>` and `Rcpp::wrap<>`. IIRC, Rcpp cannot use the `is_enum` trait because it's a C++11 thing. https://github.com/RcppCore/Rcpp/blob/f3c5a34e06e774532227470b01c63a8f08ce4313/inst/include/Rcpp/macros/module.h#L76

**Comment by jimhester** [comment]
Sure, that seems reasonable to me.

In the past I have represented enums in R as named integers. 

But I don't think it is possible to do that automatically in cpp11 until C++ has support for reflection over enums, so just doing this one way seem fine to me.

**Comment by bkietz** [comment]
I'm not sure what a named integer is. However it is possible to extract string names of types, globals, and enum members:
```c++
enum class ValueKind { NULL_, BOOLEAN, NUMBER, STRING, ARRAY, OBJECT };
constexpr ValueKind kDocumentKind = ValueKind::OBJECT;
assert(nameof<ValueKind>() == "ValueKind");
assert(nameof<ValueKind, ValueKind::BOOLEAN>() == "BOOLEAN");
assert(nameof<ValueKind, kDocumentKind>() == "kDocumentKind");
```

Would that be enough reflection to accomplish named integers ergonomically?
