### ISSUE TITLE
cpp code garbled in "Get started with cpp11" vignette online

### ISSUE THREAD

**Issue by kmiddleton** [r-lib/cpp11#68]
Following along with the "Get started with cpp11" vignette (https://cpp11.r-lib.org/articles/cpp11.html), the cpp code seems to be getting garbled when the vignette is produced. For example, the vignette example lines 117-121 (https://github.com/r-lib/cpp11/blob/master/vignettes/cpp11.Rmd)

```cpp
int one() {
  return 1;
}
```

is rendered in the vignette (https://cpp11.r-lib.org/articles/cpp11.html#no-inputs-scalar-output-1) as 

```
cpp_function('int one() {
  return 1;
}'p_function('int one() {
  return 1;
}')
```
Somehow the code isn't parsing correctly such that part of the code is pasted into itself. This might be a pkgdown issue, because my local copy of the vignette looks fine.

**Comment by jimhester** [comment]
Yeah I think it must be a pkgdown / downlit issue, the CRAN vignette is working correctly as is the local version of the vignette.

**Comment by jimhester** [comment]
Looks like it is due to this https://github.com/r-lib/downlit/issues/34
